modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="pregxxy"
version="${version}"
displayName="Pregxxy"
logoFile="assets/pregxxy/icon.png"
authors="SoccyUwU"
description='''Pregxxy adds several Hex Casting patterns related to breeding.'''
displayURL="https://github.com/SoccPuppet/heartxxy"

[[dependencies.pregxxy]]
modId="neoforge"
type="required"
versionRange="[21.1.234,)"
ordering="NONE"
side="BOTH"

[[dependencies.pregxxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.pregxxy]]
modId="kotlinforforge"
type="required"
versionRange="[5.12.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.pregxxy]]
modId="hexcasting"
type="required"
versionRange="[0.12.0-devel-pre-35,)"
ordering="AFTER"
side="BOTH"
